### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by Miliyonayalew** [Miliyonayalew/Portfolio#6]

**Comment by JustoRago** [comment]
This looks pretty good!

There's some minor issues in the cards in the mobile version, text doesn't seem to be properly cented in the language list's items and in some cases does not fit properly and wrap where it shouldn't. Some similar issues exists in the lists in the about section, along with conbtainers taking more shape than they are supposed to (possibly due to justify content being set to stretch). 

Similar issues can be seen in the browser version, along with something of a need for padding for the text.

**Comment by Kelvin-Ben** [comment]
#3 Great work
- Your project looks fine and I do not have any suggestions for any changes.
- You have adhered to Html semantics as required.
